cells_side: 24
animate_time: 6 #second
show: P1
problems:
  P0:
    desc: free fall with air frcition
    U: 1  
    V: 9.8-k*Y
    X: 
      name: time
      range: [0,20]
    Y:
      name: speed
      range: [40,50]
    args:
      k: 0.2
  P1:
    desc: demo1 by alex
    U: 1  
    V: X+1-Y
    X: 
      name: time
      range: [0,3]
    Y:
      name: speed
      range: [0,3]
  P2:
    desc: demo2 by alex
    U: cos(X)*cos(Y)   
    V: -sin(X)*sin(Y)
    X: 
      name: x
      range: [-3,3]
    Y:
      name: y
      range: [-3,3]