WIDTH: 1024
HEIGHT: 600
FPS: 60
TITLE: Space View

cells_side: 24
animate_time: 6 #second
normalize: true
ball_pos: [0,0.8] # normalize coordinate, [1,1] correspond to the top right corner of the screen
problem: 04_pendulum #01_fall,02_diffuse,03_fishing,04_pendulum